/* config.h.  Generated by configure.  */
/* config.h.in.  */
/* $Id$ */

#define SHORTRIGHT "Copyright (C) 2002-2004 M. Broek"
#define COPYRIGHT "Copyright (C) 2002-2004 Michiel Broek, All Rights Reserved"
#define VERSION "0.1.3"

/* Name of package */
/* #undef PACKAGE */

/* Define if your `struct tm' has `tm_zone'. Deprecated, use
   `HAVE_STRUCT_TM_TM_ZONE' instead. */
#define HAVE_TM_ZONE 1

